spring.application.name=weather
spring.datasource.url=jdbc:postgresql://localhost:5432/sampledb
spring.datasource.username=achyuthmohan
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL Dialect (optional in Spring Boot 3+, Hibernate detects it automatically)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
